### PR TITLE
Allow to set currency programmatically (AdaptivePayments)

### PR DESCRIPTION
**Pull request by Misiak4**
Hey,

what do you think about it? This probably can be applied on ExpressPayments too (did not checked).

Misiak

### CODE REVIEW

**Comment by Misiak4** [comment]
Btw I can update it and add brackets if needed.

If you merge this one I can create PR for ExpressPayments (and Documentation) too.

**Comment by srmklive** [comment]
I would add the ```setCurrency``` function inside the ```src/Traits/PayPalRequest.php``` file. This way it will be available to both classes. I would also make this function private. Also there is no need to check if the currency is set. It is automatically set by default to ```USD```.

**Comment by Misiak4** [comment]
Okay i will move it to Request.

Btw that check is not looking for a empty value...it will allow to set currency directly in data array:

```
$data = [
         'currency' => 'USD';
         'receivers'  => [
                [
                    'email' => email@email.com,
                    'amount' => $donationAmount,
                    'primary' => true,
                ],
                [
                    'email' => email@email.com,
                    'amount' => $userAmount,
                    'primary' => false
                ]
            ]
```

**Comment by srmklive** [comment]
can you rebase your commits too?

**Comment by Misiak4** [comment]
I re-cloned repo and cleaned it a bit :) New PR posted.

**Pull request closed without merging**
