### PR TITLE
Update PayPal API Show Total

### PR DESCRIPTION
**Pull request by tomshaw**
This update converts the show totals property to string value true or false.

### CODE REVIEW

**Comment by srmklive** [comment]
I don't think its needed here.

**Comment by tomshaw** [comment]
Actually it is need there. PayPal has no idea what total_required=1 is. Should be total_required=true.

[List invoices](https://developer.paypal.com/docs/api/invoicing/v2/#invoices_list)

`
$this->paypal->getProvider()->setPageSize($this->pageSize)->setCurrentPage($this->currentPage)->showTotals(true);
`

**Comment by srmklive** [comment]
I would not do it like this. There are also other API calls where it is needed. If you can update PR with a fix that can be used across the package, that would be great.

**Comment by tomshaw** [comment]
Absolutely. Completely agree repeating the same line of code is anti pattern. Being unfamiliar with the code base I wonder what a satisfactory solution might be? A URL builder class or helper function? Will take a look tomorrow.

**Comment by srmklive** [comment]
@tomshaw look at the referenced commit. I think this resolves the issue.

**Pull request closed without merging**
